name: apg2024
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  http: ^1.2.2
  flutter_pdfview: ^1.3.4
  webview_flutter: ^4.10.0
  english_words: ^4.0.0
  provider: ^6.0.0
  dio: ^5.7.0  
  path_provider: ^2.1.4 
  pdf_viewer_plugin: ^2.0.1
  photo_view: ^0.15.0
  pdf_render: ^1.4.12
  syncfusion_flutter_pdfviewer: ^27.1.57 
  open_filex: ^4.5.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/showcasespg.png
